### ISSUE TITLE
problems adding overlay

### ISSUE THREAD

**Issue by ernsteiswuerfel** [alexandervdm/gentoo-mate#2]
I installed the overlay weeks ago but managed to break it somehow. Now I got problems adding it again...
> layman -o https://github.com/alexandervdm/gentoo-mate/mate-vdm.xml -f -a mate-vdm

Tells me: Overlay "mate-vdm" does not exist.
> layman -o https://github.com/alexandervdm/gentoo-mate/mate-vdm.xml -f -a gentoo-mate

Adds the other mate-overlay from git://anongit.gentoo.org/proj/gentoo-mate.git

What am I missing here?

**Comment by alexandervdm** [comment]
Hi, this should work:

```layman -o https://raw.githubusercontent.com/alexandervdm/gentoo-mate/master/mate-vdm.xml -f -a mate-vdm```

If not, please let me know.

**Comment by ernsteiswuerfel** [comment]
It adds the overlay, but in subsequent emerges portage does not seem to reckognize it due to a name mismatch:

```
# layman -o https://raw.githubusercontent.com/alexandervdm/gentoo-mate/master/mate-vdm.xml -f -a mate-vdm

 * Fetching remote list...
 * Fetch Ok

* Adding overlay...
 * Overlay "mate-vdm" is not an official. Continue install? [y/n]: y
 * Running Git... # ( cd /var/lib/layman  && /usr/bin/git clone https://github.com/alexandervdm/gentoo-mate.git /var/lib/layman/mate-vdm )
Klone nach '/var/lib/layman/mate-vdm' ...
remote: Counting objects: 760, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 760 (delta 96), reused 95 (delta 95), pack-reused 634
Empfange Objekte: 100% (760/760), 313.81 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (388/388), Fertig.
Prüfe Konnektivität ... Fertig.
 * Running Git... # ( cd /var/lib/layman/mate-vdm  && /usr/bin/git config user.name "layman" )
 * Running Git... # ( cd /var/lib/layman/mate-vdm  && /usr/bin/git config user.email "layman@localhost" )
!!! Section 'mate-vdm' in repos.conf has name different from repository name 'gentoo-mate' set inside repository
 * Successfully added overlay(s) mate-vdm.
```

**Comment by alexandervdm** [comment]
I used the original repo_name to stay compatible with upstream @ gentoo, but It has been modified now and should work for you.
